-- ----------------------------
-- Table structure for message
-- ----------------------------
CREATE TABLE "message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int8 NOT NULL,
  "title" varchar(64) NOT NULL,
  "content" text  NOT NULL,
  "creation_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- Indexes structure for table message
-- ----------------------------
CREATE INDEX "idx_message_user_id" ON "message" USING btree ("user_id");
