-- ----------------------------
-- Table structure for token
-- ----------------------------
CREATE TABLE "token" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int8 NOT NULL,
  "access_token" varchar(64) NOT NULL,
  "creation_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- Indexes structure for table token
-- ----------------------------
CREATE UNIQUE INDEX "idx_token_access_token" ON "token" USING btree ("access_token");
CREATE UNIQUE INDEX "idx_token_user_id" ON "token" USING btree ("user_id");
