-- ----------------------------
-- Table structure for transport
-- ----------------------------
CREATE TABLE "transport" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int8 NOT NULL,
  "type" varchar(16) NOT NULL,
  "chat_id" varchar(64),
  "connected" bool NOT NULL,
  "creation_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- Indexes structure for table transport
-- ----------------------------
CREATE INDEX "idx_transport_user_id" ON "transport" USING btree ("user_id");
CREATE UNIQUE INDEX "idx_transport_user_id_type" ON "transport" USING btree ("user_id", "type");
