-- ----------------------------
-- Table structure for user
-- ----------------------------
CREATE TABLE "user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "open_id" uuid NOT NULL,
  "project_id" varchar (45) NOT NULL,
  "wallet_address" varchar(66) NOT NULL,
  "creation_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- Indexes structure for table user
-- ----------------------------
CREATE UNIQUE INDEX "idx_user_open_id" ON "user" USING btree ("open_id");
CREATE UNIQUE INDEX "idx_user_project_id" ON "user" USING btree ("project_id");
CREATE UNIQUE INDEX "idx_user_wallet_address" ON "user" USING btree ("wallet_address");
