-- ----------------------------
-- Table structure for user
-- ----------------------------
CREATE TABLE "user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_address" varchar(66) NOT NULL,
  "creation_time" timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------
-- Indexes structure for table user
-- ----------------------------
CREATE UNIQUE INDEX "idx_user_wallet_address" ON "user" USING btree ("wallet_address");
